routes:
  'admin/reports/documentation':
    title: Site Documentation
    description: Quick report for site setup
    access arguments: ['at-doc access']
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\Roles']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/roles':
    title: Roles
    access arguments: ['at-doc access']
    weight: -10
    type: constant('MENU_DEFAULT_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\Roles']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/input-formats':
    title: Input Formats
    access arguments: ['at-doc access']
    type: constant('MENU_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\InputFormats']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/entity':
    title: Entities
    access arguments: ['at-doc access']
    type: constant('MENU_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\Entity']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/node-types':
    title: Node Types
    access arguments: ['at-doc access']
    type: constant('MENU_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\NodeTypes']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/views':
    title: Views
    access arguments: ['at-doc access']
    type: constant('MENU_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\Views']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/modules':
    title: Modules
    access arguments: ['at-doc access']
    type: constant('MENU_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\Modules']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']

  'admin/reports/documentation/taxonomy':
    title: Taxonomy
    access arguments: ['at-doc access']
    type: constant('MENU_LOCAL_TASK')
    controller: ['Drupal\at_doc\Controller\Report', 'renderReport', ['Drupal\at_doc\Report\Taxonomy']]
    attached:
      css: ['@at_doc/misc/css/at_doc.css']
